name: Maintain a language
description: Request to become a language maintainer
title: "maintain: <language>"
labels: []
body:
  - type: input
    id: language
    attributes:
      label: What language do you want to maintain?
      description: You will be in charge of reviewing strings and can assist in assigning badges
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to your Weblate profile
      description: You will be given reviewer status to approve strings
    validations:
      required: true
  - type: input
    id: revolt-id
    attributes:
      label: Revolt user ID
      description: Used for record-keeping and assigning your profile the translator badge
    validations:
      required: true
